### ISSUE TITLE
step 1: datamodel + config import

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/hotel#1]
- use action parser & params parser to go to mem db with nicely organized structs
- use sum types
- config info is
    - employees / team
    - hotel structure e.g.rooms
    - products (all variety of what can be sold)

**Comment by jonathanouwerx** [comment]
@despiegk I have managed to put in place a working model, but I was wondering where you want me to go from here. Working model includes:
- data persistence implemented with md files (only a few pieces of dummy data entered so far)
- internal structs and logic ie a memdb with light sdk
- telegram bot at a very basic level integrated with the system
